// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZwzyZ5nAEjwA9H6u69i0kwcmXmAqRi98',
    appId: '1:49184985365:web:8301f4a0affde7ed39991c',
    messagingSenderId: '49184985365',
    projectId: 'utopia-app-26',
    authDomain: 'utopia-app-26.firebaseapp.com',
    storageBucket: 'utopia-app-26.firebasestorage.app',
    measurementId: 'G-8KLZ58Q2MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBliHUdNpFHD4A3mnXYlRDgKHP4hQhIA5g',
    appId: '1:49184985365:android:41c18777b994d3e139991c',
    messagingSenderId: '49184985365',
    projectId: 'utopia-app-26',
    storageBucket: 'utopia-app-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSpepd6_upYsyvPHhFNKl0nTONbiL-F-k',
    appId: '1:49184985365:ios:1679554e8bbc900e39991c',
    messagingSenderId: '49184985365',
    projectId: 'utopia-app-26',
    storageBucket: 'utopia-app-26.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSpepd6_upYsyvPHhFNKl0nTONbiL-F-k',
    appId: '1:49184985365:ios:1679554e8bbc900e39991c',
    messagingSenderId: '49184985365',
    projectId: 'utopia-app-26',
    storageBucket: 'utopia-app-26.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZwzyZ5nAEjwA9H6u69i0kwcmXmAqRi98',
    appId: '1:49184985365:web:ce6861031f95554939991c',
    messagingSenderId: '49184985365',
    projectId: 'utopia-app-26',
    authDomain: 'utopia-app-26.firebaseapp.com',
    storageBucket: 'utopia-app-26.firebasestorage.app',
    measurementId: 'G-HPHSNYYCRN',
  );
}
